### Encode categorical variable

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [3]:
#Step 2: Load your dataset

df = pd.read_csv('D:\data analyst\ML project\ecommerce-churn-prediction\data\data_ecommerce_customer_churn.csv')
df.head()

<>:3: SyntaxWarning: invalid escape sequence '\d'
<>:3: SyntaxWarning: invalid escape sequence '\d'
C:\Users\DELL\AppData\Local\Temp\ipykernel_15436\1104475997.py:3: SyntaxWarning: invalid escape sequence '\d'
  df = pd.read_csv('D:\data analyst\ML project\ecommerce-churn-prediction\data\data_ecommerce_customer_churn.csv')


Tenure  WarehouseToHome  NumberOfDeviceRegistered    PreferedOrderCat  \
0    15.0             29.0                         4  Laptop & Accessory   
1     7.0             25.0                         4              Mobile   
2    27.0             13.0                         3  Laptop & Accessory   
3    20.0             25.0                         4             Fashion   
4    30.0             15.0                         4              Others   

   SatisfactionScore MaritalStatus  NumberOfAddress  Complain  \
0                  3        Single                2         0   
1                  1       Married                2         0   
2                  1       Married                5         0   
3                  3      Divorced                7         0   
4                  4        Single                8         0   

   DaySinceLastOrder  CashbackAmount  Churn  
0                7.0          143.32      0  
1                7.0          129.29      0  
2                7.0          168.54      0  
3                NaN          230.27      0  
4                8.0          322.17      0

### Encode Categorical Variables

In [4]:
# Print unique values before encoding
print("\nUnique values in PreferedOrderCat:", df['PreferedOrderCat'].unique())
print("Unique values in MaritalStatus:", df['MaritalStatus'].unique())


Unique values in PreferedOrderCat: ['Laptop & Accessory' 'Mobile' 'Fashion' 'Others' 'Mobile Phone' 'Grocery']
Unique values in MaritalStatus: ['Single' 'Married' 'Divorced']


In [5]:
df = pd.get_dummies(df, columns=['PreferedOrderCat', 'MaritalStatus'], drop_first=True)

In [6]:
df.head()

Tenure  WarehouseToHome  NumberOfDeviceRegistered  SatisfactionScore  \
0    15.0             29.0                         4                  3   
1     7.0             25.0                         4                  1   
2    27.0             13.0                         3                  1   
3    20.0             25.0                         4                  3   
4    30.0             15.0                         4                  4   

   NumberOfAddress  Complain  DaySinceLastOrder  CashbackAmount  Churn  \
0                2         0                7.0          143.32      0   
1                2         0                7.0          129.29      0   
2                5         0                7.0          168.54      0   
3                7         0                NaN          230.27      0   
4                8         0                8.0          322.17      0   

   PreferedOrderCat_Grocery  PreferedOrderCat_Laptop & Accessory  \
0                     False                                 True   
1                     False                                False   
2                     False                                 True   
3                     False                                False   
4                     False                                False   

   PreferedOrderCat_Mobile  PreferedOrderCat_Mobile Phone  \
0                    False                          False   
1                     True                          False   
2                    False                          False   
3                    False                          False   
4                    False                          False   

   PreferedOrderCat_Others  MaritalStatus_Married  MaritalStatus_Single  
0                    False                  False                  True  
1                    False                   True                 False  
2                    False                   True                 False  
3                    False                  False                 False  
4                     True                  False                  True

### check for duplicates

In [7]:
duplicates = df.duplicated().sum()
print(f"\nDuplicate rows: {duplicates}")
df.drop_duplicates(inplace=True)


Duplicate rows: 671


In [8]:
print(df.duplicated().sum())

0


In [9]:
df.head()

Tenure  WarehouseToHome  NumberOfDeviceRegistered  SatisfactionScore  \
0    15.0             29.0                         4                  3   
1     7.0             25.0                         4                  1   
2    27.0             13.0                         3                  1   
3    20.0             25.0                         4                  3   
4    30.0             15.0                         4                  4   

   NumberOfAddress  Complain  DaySinceLastOrder  CashbackAmount  Churn  \
0                2         0                7.0          143.32      0   
1                2         0                7.0          129.29      0   
2                5         0                7.0          168.54      0   
3                7         0                NaN          230.27      0   
4                8         0                8.0          322.17      0   

   PreferedOrderCat_Grocery  PreferedOrderCat_Laptop & Accessory  \
0                     False                                 True   
1                     False                                False   
2                     False                                 True   
3                     False                                False   
4                     False                                False   

   PreferedOrderCat_Mobile  PreferedOrderCat_Mobile Phone  \
0                    False                          False   
1                     True                          False   
2                    False                          False   
3                    False                          False   
4                    False                          False   

   PreferedOrderCat_Others  MaritalStatus_Married  MaritalStatus_Single  
0                    False                  False                  True  
1                    False                   True                 False  
2                    False                   True                 False  
3                    False                  False                 False  
4                     True                  False                  True

### Normalize/Scale Numeric Features

In [10]:
numeric_cols = ['Tenure', 'WarehouseToHome', 'NumberOfDeviceRegistered', 'SatisfactionScore',
                'NumberOfAddress', 'Complain', 'DaySinceLastOrder', 'CashbackAmount']
scaler = StandardScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])   

In [11]:
df.head()

Tenure  WarehouseToHome  NumberOfDeviceRegistered  SatisfactionScore  \
0  0.556065         1.574601                  0.318066          -0.014908   
1 -0.368851         1.107694                  0.318066          -1.448703   
2  1.943440        -0.293027                 -0.664992          -1.448703   
3  1.134138         1.107694                  0.318066          -0.014908   
4  2.290283        -0.059573                  0.318066           0.701990   

   NumberOfAddress  Complain  DaySinceLastOrder  CashbackAmount  Churn  \
0        -0.847545 -0.626164           0.664204       -0.691593      0   
1        -0.847545 -0.626164           0.664204       -0.976159      0   
2         0.296274 -0.626164           0.664204       -0.180063      0   
3         1.058819 -0.626164                NaN        1.071988      0   
4         1.440092 -0.626164           0.934809        2.935968      0   

   PreferedOrderCat_Grocery  PreferedOrderCat_Laptop & Accessory  \
0                     False                                 True   
1                     False                                False   
2                     False                                 True   
3                     False                                False   
4                     False                                False   

   PreferedOrderCat_Mobile  PreferedOrderCat_Mobile Phone  \
0                    False                          False   
1                     True                          False   
2                    False                          False   
3                    False                          False   
4                    False                          False   

   PreferedOrderCat_Others  MaritalStatus_Married  MaritalStatus_Single  
0                    False                  False                  True  
1                    False                   True                 False  
2                    False                   True                 False  
3                    False                  False                 False  
4                     True                  False                  True

### Feature Selection (Optional - filter out highly correlated/redundant ones)

In [12]:
correlation_matrix = df.corr()
# Show correlation with target
print(correlation_matrix['Churn'].sort_values(ascending=False))

Churn                                  1.000000
Complain                               0.262278
MaritalStatus_Single                   0.172694
PreferedOrderCat_Mobile Phone          0.152569
PreferedOrderCat_Mobile                0.117303
NumberOfDeviceRegistered               0.109612
SatisfactionScore                      0.098393
WarehouseToHome                        0.074237
NumberOfAddress                        0.046354
PreferedOrderCat_Others               -0.052891
PreferedOrderCat_Grocery              -0.092952
PreferedOrderCat_Laptop & Accessory   -0.135448
DaySinceLastOrder                     -0.147918
MaritalStatus_Married                 -0.151188
CashbackAmount                        -0.151475
Tenure                                -0.348654
Name: Churn, dtype: float64


In [13]:
df.isnull().sum()

Tenure                                 160
WarehouseToHome                        135
NumberOfDeviceRegistered                 0
SatisfactionScore                        0
NumberOfAddress                          0
Complain                                 0
DaySinceLastOrder                      181
CashbackAmount                           0
Churn                                    0
PreferedOrderCat_Grocery                 0
PreferedOrderCat_Laptop & Accessory      0
PreferedOrderCat_Mobile                  0
PreferedOrderCat_Mobile Phone            0
PreferedOrderCat_Others                  0
MaritalStatus_Married                    0
MaritalStatus_Single                     0
dtype: int64

In [14]:
df = df.dropna()

### saving cleaned data

In [15]:
df.to_csv('../data/processed/churn_preprocessed.csv', index=False)

### Model training

In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [17]:
# Train test split

df = pd.read_csv('../data/processed/churn_preprocessed.csv')

In [18]:
X = df.drop('Churn', axis=1)
y = df['Churn']

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 6: Train Logistic Regression model
log_model = LogisticRegression(max_iter=1000)
log_model.fit(X_train, Y_train)

# Step 7: Make predictions
y_pred = log_model.predict(X_test)

# Step 8: Evaluate the model
print("Logistic Regression Results:\n")
print("Accuracy Score:", accuracy_score(Y_test, y_pred))
print("\nClassification Report:\n", classification_report(Y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(Y_test, y_pred))

Logistic Regression Results:

Accuracy Score: 0.9051878354203936

Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.97      0.95       478
           1       0.76      0.51      0.61        81

    accuracy                           0.91       559
   macro avg       0.84      0.74      0.78       559
weighted avg       0.90      0.91      0.90       559


Confusion Matrix:
 [[465  13]
 [ 40  41]]


## random forest

In [19]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, Y_train)

# Step 8: Predict and evaluate
y_pred = rf_model.predict(X_test)

print("Random Forest Results:\n")
print("Accuracy Score:", accuracy_score(Y_test, y_pred))
print("\nClassification Report:\n", classification_report(Y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(Y_test, y_pred))

Random Forest Results:

Accuracy Score: 0.9069767441860465

Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.97      0.95       478
           1       0.76      0.52      0.62        81

    accuracy                           0.91       559
   macro avg       0.84      0.75      0.78       559
weighted avg       0.90      0.91      0.90       559


Confusion Matrix:
 [[465  13]
 [ 39  42]]


### XG BOOST

In [20]:
xgb_model = XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)
xgb_model.fit(X_train, Y_train)

# Step 8: Make predictions
y_pred = xgb_model.predict(X_test)

# Step 9: Evaluate the model
print("XGBoost Classifier Results:\n")
print("Accuracy Score:", accuracy_score(Y_test, y_pred))
print("\nClassification Report:\n", classification_report(Y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(Y_test, y_pred))

XGBoost Classifier Results:

Accuracy Score: 0.9302325581395349

Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.97      0.96       478
           1       0.78      0.72      0.75        81

    accuracy                           0.93       559
   macro avg       0.87      0.84      0.85       559
weighted avg       0.93      0.93      0.93       559


Confusion Matrix:
 [[462  16]
 [ 23  58]]


d:\data analyst\ML project\ecommerce-churn-prediction\venv\Lib\site-packages\xgboost\training.py:183: UserWarning: [18:43:34] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


In [21]:
# Save Model
import joblib
joblib.dump(xgb_model,'../models/final_xgb_model.pkl')

['../models/final_xgb_model.pkl']